### ISSUE TITLE
Fix Jackson error in SignalAggregator service

### ISSUE THREAD

**Issue by ezeev** [ezeev/viroonga-search#8]
```
objc[492]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/bin/java (0x100c1d4c0) and /Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/libinstrument.dylib (0x100ca94e0). One of the two will be used. Which one is undefined.
Exception in thread "main" com.fasterxml.jackson.core.JsonParseException: Unexpected character ('"' (code 34)): was expecting comma to separate Object entries
 at [Source: (byte[])"{
  "kafkaBootstrapServers": "localhost:9092",
  "kafkaConsumerGroupId": "group2",
  "kafkaConsumerTopic": "bb-signals",
  "solrUrl": "http://localhost:8983/solr",
  "solrCollection": "bb-signals",
  "expectedFieldCount": 6,
  "dimension1Position": 2,
  "dimension2Position": 5,
  "windowLength": 1200,
  "solrDimension1Field": "query_txt_en",
  "solrDimension2Field": "product_id_s"
  "solrCountField": "count_i",
  "solrTimestampField": "timestamp_l"
}"; line: 13, column: 4]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1804)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:663)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:561)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:707)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:401)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1280)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4001)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3079)
	at com.viroonga.search.SignalAggregatorServiceApplication.main(SignalAggregatorServiceApplication.java:15)

Process finished with exit code 1
```

**Comment by ezeev** [comment]
Fixed. Json was in fact valid. Everything is working as expected. The issue was that I missed a comma when updating the queryToProductAggr.js file
